<?php
    /** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
    /** @var $viewModel \MageSuite\DailyDeal\ViewModel\DailyDealCounter */
    /** @var $block \MageSuite\DailyDeal\Block\Product */
    $product = $block->getProduct();
    $dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
    $dailyDealData = $dailyDealHelper->prepareOfferData($product);
    $dailyDealCounterPlace = $block->getCounterPlace() ? $block->getCounterPlace() : 'pdp';
?>
<?php
    if ($product->getIsSalable() && $viewModel->isDailyDealCounterApplicable($dailyDealData, $dailyDealCounterPlace)):
    $headerLabel = $block->getItemsLeftLabel();
?>
    <div class="cs-dailydeal <?= $block->getAdditionalCssClasses() ?> <?php if ($dailyDealData['items'] and $block->getShowHeader()): echo $block->getModifierForQtyLimitation(); endif; ?>"
        data-phrase-day="<?= __('Day') ?>"
        data-phrase-days="<?= __('Days') ?>"
        data-phrase-hour="<?= __('Hour') ?>"
        data-phrase-hours="<?= __('Hours') ?>"
        data-phrase-minute="<?= __('Min') ?>"
        data-phrase-minutes="<?= __('Min') ?>"
        data-phrase-second="<?= __('Sec') ?>"
        data-phrase-seconds="<?= __('Sec') ?>"
    >
        <?= $block->getChildHtml('hotspot.before.header') ?>
        <?php if ($dailyDealData['items'] and $block->getShowHeader()): ?>
            <?php
                $headerTitle = $block->getHeaderTitle();
            ?>
            <div class="cs-dailydeal__header">
                <?php if(isset($headerTitle) and !empty($headerTitle)): ?>
                    <p class="cs-dailydeal__title"><?= $headerTitle ?></p>
                <?php endif; ?>
                <div class="cs-dailydeal__availability">
                    <?= $block->getAvailabilityTextBefore() ?>
                    <span class="cs-dailydeal__items-amount" data-dailydeal-items="<?= $dailyDealData['items'] ?>">
                        <?= $dailyDealData['items'] ?> 
                    </span> 
                    <?= $block->getAvailabilityTextAfter() ?>
                </div>
            </div>
        <?php endif; ?>
        <?= $block->getChildHtml('hotspot.before.countdown') ?>
        <div class="cs-dailydeal__countdown" data-dailydeal-end="<?= $dailyDealData['to'] ?>"></div>
        <?= $block->getChildHtml('hotspot.after.countdown') ?>
    </div>
<?php endif; ?>
