<?php
$dailyDealData = $block->getOfferData();

if($dailyDealData && $dailyDealData['deal']){
    echo $this->getLayout()->createBlock(
        'MageSuite\Frontend\Block\Twig', 'daily-deal-pdp', [
            'data' => [
                'namespace' => 'cs-',
                'header' => [
                    'show' => true,
                    'title' => __('Limited time offer')
                ],
                'items' => [
                    'textBefore' => '',
                    'textAfter' => __('items left'),
                    'amount' => $dailyDealData['items']
                ],
                'deal' => [
                    'end' => $dailyDealData['to']
                ]
            ]
        ]
    )->setTemplate("dailydeal/dailydeal.twig")->toHtml();
} 
?>
