<?php
/** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');

if ($dailyDealHelper->isOfferEnabled($block->getProduct())):
    $dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());
    ?>
    <?php if ($dailyDealData and $dailyDealData['deal'] and in_array($dailyDealData['displayType'], ['badge', 'badge_counter']) && $dailyDealData['items'] && $dailyDealData['items'] > 0): ?>
    <?php
    $wrapperTag = $block->getWrapperTag() ?? 'li';

    $wrapperClass = $block->getWrapperCssClass();
    $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';
    // Don't hide badge by default if it is a compact scenario without counter.
    $wrapperStyle = $dailyDealData['displayType'] === 'badge' ? '' : 'style="display: none"';

    $cssClass = $block->getCssClass();
    $cssClass = $cssClass ? sprintf('class="%s"', $cssClass) : '';

    $badgeTextClass = $block->getTextCssClass();
    $badgeTextClass = $badgeTextClass ? sprintf('class="%s"', $badgeTextClass) : '';

    $label = $block->getLabel() ?? __('Limited offer');

    $amount = $block->getAmountPresentationFormat();
    $amount = $dailyDealData['initialAmount'] && !empty($amount) ? __($amount, $dailyDealData['items'], $dailyDealData['initialAmount']) : '';
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?> <?= $wrapperStyle ?>>
    <span <?= $cssClass ?>>
        <?php if ($label): ?>
            <span <?= $badgeTextClass ?>><?= $label ?></span>
        <?php endif; ?>
        <?php if ($amount): ?>
            <span <?= $badgeTextClass ?>><?= $amount ?></span>
        <?php endif; ?>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
<?php endif; ?>
