<?php
/** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());
?>
<?php if($dailyDealData and $dailyDealData['deal'] and in_array($dailyDealData['displayType'], ['badge', 'badge_counter']) && $dailyDealData['items'] && $dailyDealData['items'] > 0): ?>
    <?php
        $wrapperTag = $block->getWrapperTag() ? $block->getWrapperTag() : 'li';
        $wrapperClass = $block->getWrapperCssClass() ? sprintf('class="%s"', $block->getWrapperCssClass()) : '';
        $cssClass = $block->getCssClass() ? sprintf('class="%s"', $block->getCssClass()) : '';
        $badgeTextClass = $block->getTextCssClass() ? sprintf('class="%s"', $block->getTextCssClass()) : '';
        $label = !empty($block->getLabel()) ? $block->getLabel() : __('Limited offer');
        $amount = $dailyDealData['initialAmount'] && !empty($block->getAmountPresentationFormat()) ? __($block->getAmountPresentationFormat(), $dailyDealData['items'], $dailyDealData['initialAmount']) : '';
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?> style="display: none">
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $label ?> <span><?= $amount ?></span></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
