<?php
/** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());
?>
<?php if($dailyDealData and $dailyDealData['deal'] and in_array($dailyDealData['displayType'], ['badge', 'badge_counter']) && $dailyDealData['items'] && $dailyDealData['items'] > 0): ?>
    <?php
        $wrapperTag = $block->getWrapperTag() ?? 'li';

        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $cssClass = $block->getCssClass();
        $cssClass = $cssClass ? sprintf('class="%s"', $cssClass) : '';

        $badgeTextClass = $block->getTextCssClass();
        $badgeTextClass = $badgeTextClass ? sprintf('class="%s"', $badgeTextClass) : '';

        $label = $block->getLabel() ?? __('Limited offer');

        $amount = $block->getAmountPresentationFormat();
        $amount = $dailyDealData['initialAmount'] && !empty($amount) ? __($amount, $dailyDealData['items'], $dailyDealData['initialAmount']) : '';
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?> style="display: none">
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $label ?> <span><?= $amount ?></span></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
