<?php
    /** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
    $dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
    $dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());
?>
<?php if($dailyDealData and $dailyDealData['deal'] and $dailyDealData['displayType'] == 'badge_counter'): ?>
    <?php $headerLabel = $block->getItemsLeftLabel(); ?>
    <div class="cs-dailydeal cs-dailydeal--tile">
        <?php if ($dailyDealData['items'] and $dailyDealData['items'] > 0 and !empty($headerLabel)): ?>
            <div class="cs-dailydeal__header">
                <div class="cs-dailydeal__availability">
                    <strong class="cs-dailydeal__items-amount"
                            data-dailydeal-items="<?= $dailyDealData['items'] ?>"><?= $dailyDealData['items'] ?></strong> <?= $headerLabel ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="cs-dailydeal__countdown" data-dailydeal-end="<?= $dailyDealData['to'] ?>"></div>
        <input type="hidden" name="cs-dailydeal__countdown-labels" class="cs-dailydeal__countdown-labels" value='<?=json_encode($block->getCountdownLabels())?>'>
    </div>
<?php endif; ?>

