<?php
    /** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
    $dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');

    if($dailyDealHelper->isOfferEnabled($block->getProduct())):

    $dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());

    $dailyDealDiscount = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['dailyDiscount'] : '';
?>
<?php if ($dailyDealDiscount and $dailyDealData['displayType'] === 'badge_counter'): ?>
    <?php
        $wrapperTag = $block->getWrapperTag() ?? 'li';

        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $cssClass = $block->getCssClass();
        $cssClass = $cssClass ? sprintf('class="%s"', $cssClass) : '';

        $badgeTextClass = $block->getTextCssClass();
        $badgeTextClass = $badgeTextClass ? sprintf('class="%s"', $badgeTextClass) : '';

        $label = $block->getLabel();

        $valuePrefix = $block->getValuePrefix();
        $valueSuffix = $block->getValueSuffix();

        $showNumericValue = $block->getShowNumericValue();
        $showNumericValue = $showNumericValue ? $dailyDealDiscount : '';
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?> style="display: none">
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $label ?> <span><?= $valuePrefix ?><?= $showNumericValue ?><?= $valueSuffix ?></span></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
<?php endif; ?>
