<?php
    /** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
    $dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
    $dailyDealData = $dailyDealHelper->prepareOfferData($block->getProduct());

    $oldDiscount = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['oldDiscount'] : '';
?>
<?php if ($oldDiscount and $dailyDealData['displayType'] === 'badge_counter'): ?>
    <?php
        $wrapperTag = $block->getWrapperTag() ? $block->getWrapperTag() : 'li';
        $wrapperClass = $block->getWrapperCssClass() ? sprintf('class="%s"', $block->getWrapperCssClass()) : '';
        $cssClass = $block->getCssClass();
        $cssClass = !empty($cssClass) ? sprintf('class="%s"', $cssClass) : '';
        $label = $block->getLabel();
        $badgeTextClass = $block->getTextCssClass() ? sprintf('class="%s"', $block->getTextCssClass()) : '';

        $valuePrefix = $block->getValuePrefix();
        $valueSuffix = $block->getValueSuffix();
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?> style="display: none">
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $label ?> <span><?= $valuePrefix ?><?= $oldDiscount ?><?= $valueSuffix ?></span></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
