<?php
$product = $block->getProduct();
/** @var \MageSuite\DailyDeal\Helper\OfferData $dailyDealHelper */
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($product);

$dailyDealDiscount = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['dailyDiscount'] : '';
?>
<?php if ($product->getIsSalable() && $dailyDealDiscount) : ?>
    <?php
        $wrapperTag = $block->getWrapperTag() ?? 'li';

        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $cssClass = $block->getCssClass();
        $cssClass = $cssClass ? sprintf('class="%s"', $cssClass) : '';

        $badgeTextClass = $block->getTextCssClass();
        $badgeTextClass = $badgeTextClass ? sprintf('class="%s"', $badgeTextClass) : '';
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?>>
        <span <?= $cssClass ?>>
            <span <?= $badgeTextClass ?>><?= $block->getChildHtml('product.page.badge.dailydeal.icon') ?></span>
        </span>
    </<?= $wrapperTag ?>>
<?php endif; ?>
